services:
  postgres:
    image: postgres
    container_name: postgres_test
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: intbnk_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test